---
- name: Setup and Upgrade K8s
  hosts: localhost
  become: true
  tasks:

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        state: present

    - name: Add K8s apt repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: "kubernetes"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest

    - name: Initialize K8s
      shell: |
        kubeadm init --pod-network-cidr=10.244.0.0/16
      register: init_output
      ignore_errors: yes

    - name: Copy kubeconfig
      copy:
        content: "{{ init_output.stdout_lines | join('\n') }}"
        dest: "/home/acsakvari/.kube/config"
        owner: acsakvari
        group: acsakvari
        mode: '0644'
      when: init_output is defined

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command
      when: init_output is defined and init_output.rc == 0

    - name: Join worker node to the Kubernetes cluster
      shell: "{{ join_command.stdout }}"
      when: join_command is defined

    - name: Upgrade K8s packages
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: latest

    - name: Perform K8s upgrade using kubeadm
      shell: |
        kubeadm upgrade apply --yes
