---
- name: Deploy and Upgrade Portainer on Kubernetes
  hosts: localhost
  become: true
  tasks:

    - name: Deploy Portainer
      shell: |
        kubectl create namespace portainer || echo "Namespace already exists"
        kubectl apply -f https://raw.githubusercontent.com/portainer/portainer/master/k8s/portainer.yaml
      register: portainer_deploy
      when: inventory_hostname == 'k8-master'

    - name: Check and remove old Portainer
      shell: |
        kubectl delete deployment portainer -n portainer || echo "Portainer not installed"
      ignore_errors: yes
      when: inventory_hostname == 'k8-master'

    - name: Apply the new Portainer version
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/portainer/portainer/master/k8s/portainer.yaml
      register: portainer_upgrade
      when: inventory_hostname == 'k8-master'
